# Site settings
title: Mike Lowen
url: "http://mike.lowen.co.nz"

timezone: Pacific/Auckland

permalink: /:categories/:year/:month/:day/:title/
disqus_shortname: mikelowen

exclude:
  - diagrams

safe: true
lsi: false
