# Site settings
title: Mike Lowen
url: "http://mike.lowen.co.nz" # the base hostname & protocol for your site

# Build settings
highlighter: rouge
markdown: redcarpet

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink"]

permalink: /:categories/:year/:month/:day/:title/
disqus_shortname: mikelowen
