# Site settings
title: Mike Lowen
url: "http://mike.lowen.co.nz"

highlighter: rouge

kramdown:
  input: GFM

timezone: Pacific/Auckland

permalink: /:categories/:year/:month/:day/:title/
disqus_shortname: mikelowen

safe: true
lsi: false
