# Site settings
title: Mike Lowen
url: "http://mike.lowen.co.nz" # the base hostname & protocol for your site

kramdown:
  input: GFM
  syntax_highlighter: rouge

timezone: Pacific/Auckland

permalink: /:categories/:year/:month/:day/:title/
disqus_shortname: mikelowen

safe: true
lsi: false
