# Site settings
title: Mike Lowen
url: "http://mike.lowen.co.nz"

markdown: redcarpet
highlighter: pygments

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables" ]

timezone: Pacific/Auckland

permalink: /:categories/:year/:month/:day/:title/
disqus_shortname: mikelowen

safe: true
lsi: false
